trigger: none

parameters:
  - name: serviceConnection
    type: string
    default: 'ado-sp'

pool: 'container-pool'

stages:
  - template: ./templates/stages/terragrunt.yaml
    parameters:
      deployEnvironments:
        - environment: sandbox
          region: eastus
          environmentNumber: 000
          azureEnvironment: tg-rg-sandbox-eastus-000
        - environment: qa
          region: eastus
          environmentNumber: 000
          azureEnvironment: tg-rg-qa-eastus-000
          dependsOn:
            - sandbox_eastus_000_deploy
      subscription: ${{ parameters.serviceConnection }}
      pool: 'container-pool'