trigger: none

parameters:
  - name: serviceConnection
    type: string
    default: 'ado-sp'

pool: 'container-pool'

stages:
  - template: ./templates/stages/terragrunt.yaml
    parameters:
      deployEnvironments:
        - environment: sandbox
          azureEnvironment: tg-rg-sandbox
          terragruntPath: 'env/sandbox/eastus/000'
        - environment: qa
          azureEnvironment: tg-rg-qa
          terragruntPath: 'env/qa/eastus/000'
          dependsOn:
            - sandbox_deploy
      subscription: ${{ parameters.serviceConnection }}
      pool: 'container-pool'